## GRIB: listing contents

We will work with a GRIB file containing 6 messages, which we get as a sample (see :ref:`from_source() <data-sources-sample>`).

In [1]:
import earthkit.data as ekd
ds = ekd.from_source("sample", "test6.grib").to_fieldlist()

test6.grib:   0%|          | 0.00/1.41k [00:00<?, ?B/s]

### Using ls(), head() and tail()

All these methods (see e.g.: :py:meth:`~data.core.fieldlist.FieldList.ls`) take the same set of keyword arguments:

- n: number of messages to list
- keys: the metadata keys to dump
- extra_keys: extra keys of top of the default set of keys
- component: the field component(s) to use

#### ls()

py:meth:`~data.core.fieldlist.FieldList.ls`)  lists all the fields:

In [2]:
ds.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
1,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
2,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
3,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll
4,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll
5,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll

The number of fields can be passed as an argument:

In [3]:
ds.ls(2)

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
1,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll

In [4]:
ds.ls(n=2)

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
1,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll

##### Keys and extra keys

We can use our own list of keys instead of the default ones.

In [5]:
ds.ls(keys="time.base_datetime")

   time.base_datetime
0 2018-08-01 12:00:00
1 2018-08-01 12:00:00
2 2018-08-01 12:00:00
3 2018-08-01 12:00:00
4 2018-08-01 12:00:00
5 2018-08-01 12:00:00

In [6]:
ds.ls(keys=["time.base_datetime", "vertical.level"])

   time.base_datetime  vertical.level
0 2018-08-01 12:00:00            1000
1 2018-08-01 12:00:00            1000
2 2018-08-01 12:00:00            1000
3 2018-08-01 12:00:00             850
4 2018-08-01 12:00:00             850
5 2018-08-01 12:00:00             850

The default list of keys can be extended with ``extra_keys``:

In [7]:
ds.head(extra_keys="parameter.units")

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type,parameter.units
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll,kelvin
1,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll,meter / second
2,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll,meter / second
3,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll,kelvin
4,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll,meter / second

##### Components

We can list all the keys from one or more Field component:

In [8]:
ds.ls(component="time")

TypeError: IndexFieldListBase.ls() got an unexpected keyword argument 'component'

In [ ]:
ds.ls(component=["parameter", "time"])

It is possible to use any [ecCodes GRIB namespace](https://confluence.ecmwf.int/display/UDOC/What+are+namespaces+-+ecCodes+GRIB+FAQ):

In [ ]:
ds.ls(component="metadata", filter="ls")

#### tail()

:py:meth:`~data.readers.grib.index.GribFieldList.tail` displays the last 5 messages by default:

In [ ]:
ds.tail(5)

#### ls()

By default :py:meth:`~data.readers.grib.index.GribFieldList.ls` lists all the fields:

In [ ]:
ds.ls()

The number of fields to list can also be specified:

In [ ]:
ds.ls(2)

In [ ]:
ds.ls(-2)

### Using describe

With :py:meth:`~data.readers.grib.index.GribFieldList.describe` the contents of the fieldlist is presented in a concise way.

In [ ]:
#ds.describe()

:py:meth:`~data.readers.grib.index.GribFieldList.describe` can be used with a given parameter (defined by variable or paramId):

In [ ]:
#ds.describe("t")

In [ ]:
#ds.describe(131)

### Getting namespaces

The field namespaces can be collected as a dict via the namespace() method:

In [ ]:
ds[0].dump("parameter")

In [ ]:
ds[0].dump(["parameter", "time"])

In [ ]:
ds[0].dump()

With this method we can also inspect any [ecCodes GRIB namespace](https://confluence.ecmwf.int/display/UDOC/What+are+namespaces+-+ecCodes+GRIB+FAQ):

In [ ]:
ds[0].dump(part="metadata", filter="ls")

In [ ]:
ds[0].dump("metadata")

### Using dump

The :py:meth:`~data.readers.grib.codes.GribField.dump` method generates a tabbed interface with the fields content in a Jupyter notebook providing some interactivity. 

By default all the field namespaces are dumped.

In [ ]:
ds[0].dump()

We can dump a given namespace or namespaces.

In [ ]:
ds[0].dump("parameter")

In [ ]:
ds[0].dump(["parameter", "time"])

The [ecCodes GRIB namespaces](https://confluence.ecmwf.int/display/UDOC/What+are+namespaces+-+ecCodes+GRIB+FAQ) can also be used in  :py:meth:`~data.readers.grib.codes.GribField.dump`.

In [ ]:
# get all the ecCodes GRIB namespaces
ds[0].dump("grib")

In [ ]:
# get a given ecCodes GRIB namespace
ds[0].dump("grib.ls")