## Reading multiple files

First we prepare the data.

In [1]:
import earthkit.data as ekd
ekd.download_example_file(["test.grib", "test4.grib"])

In [2]:
!test -d _grib_dir_no_sql || (mkdir -p _grib_dir_no_sql; cp -f test.grib test4.grib _grib_dir_no_sql/)

Multiple GRIB files can be :ref:`read <data-sources-file>` in various ways:

### Option 1: using wildcards

In [3]:
fs = ekd.from_source("file", "test*.grib").to_fieldlist()

In [4]:
len(fs)

12

In [5]:
fs

### Option 2: using a list

In [6]:
fs = ekd.from_source("file", ["test.grib", "test4.grib"]).to_fieldlist()

In [7]:
len(fs)

6

In [8]:
fs

### Option 3: reading all files in a directory

In [9]:
fs = ekd.from_source("file", "./_grib_dir_no_sql").to_fieldlist()

In [10]:
len(fs)

6

In [11]:
fs

### Working with the object

The resulting GRIB object behaves in the same way as if it was created from a single file:

In [12]:
fs.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,2t,2020-05-13 12:00:00,2020-05-13 12:00:00,0 days,0,surface,0,regular_ll
1,msl,2020-05-13 12:00:00,2020-05-13 12:00:00,0 days,0,surface,0,regular_ll
2,t,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,500,pressure,0,regular_ll
3,z,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,500,pressure,0,regular_ll
4,t,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,850,pressure,0,regular_ll
5,z,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,850,pressure,0,regular_ll

In [13]:
fs[2]

Field(t, 2007-01-01 12:00:00, 2007-01-01 12:00:00, 0:00:00, 500, pressure, 0, regular_ll)

In [14]:
g = fs[1:6]
g.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,msl,2020-05-13 12:00:00,2020-05-13 12:00:00,0 days,0,surface,0,regular_ll
1,t,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,500,pressure,0,regular_ll
2,z,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,500,pressure,0,regular_ll
3,t,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,850,pressure,0,regular_ll
4,z,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,850,pressure,0,regular_ll

In [15]:
g = fs[3:6].sel({"parameter.variable": "z"}).order_by("vertical.level")
g.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,z,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,500,pressure,0,regular_ll
1,z,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,850,pressure,0,regular_ll