## NetCDF: working with fieldlists

We :ref:`read <data-sources-file>` a NetCDF file containing 3 variables on pressure levels on a 2D latitude-longitude grid. First we ensure the example file is available.

In [1]:
import earthkit.data as ekd
ekd.download_example_file("tuv_pl.nc")

In [2]:
ds = ekd.from_source("file", "tuv_pl.nc").to_fieldlist()

Our NetCDF data is represented as a :py:class:`~data.core.fieldlist.FieldList` consisting of NetCDFFields. :py:class:`~data.core.fieldlist.Field` in this context means a 2D geographical coverage (horizontal slices).

### Iteration

We can itearte through the fields (we use the first 3 fields for simplicity):

In [3]:
for f in ds[:3]:
    print(f)

Field(t, 2018-08-01 12:00:00, 2018-08-01 12:00:00, 0:00:00, 1000, pressure, 0, None)
Field(t, 2018-08-01 12:00:00, 2018-08-01 12:00:00, 0:00:00, 850, pressure, 0, None)
Field(t, 2018-08-01 12:00:00, 2018-08-01 12:00:00, 0:00:00, 700, pressure, 0, None)

### Inspecting the contents

In [4]:
len(ds)

18

In [5]:
ds.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,None
1,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,None
2,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,700,pressure,0,None
3,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,500,pressure,0,None
4,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,400,pressure,0,None
5,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,300,pressure,0,None
6,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,None
7,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,None
8,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,700,pressure,0,None
9,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,500,pressure,0,None
10,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,400,pressure,0,None
11,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,300,pressure,0,None
12,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,None
13,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,None
14,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,700,pressure,0,None
15,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,500,pressure,0,None
16,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,400,pressure,0,None
17,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,300,pressure,0,None

### Slicing

Standard Python slicing is available.

In [6]:
g = ds[1]
g

Field(t, 2018-08-01 12:00:00, 2018-08-01 12:00:00, 0:00:00, 850, pressure, 0, None)

In [7]:
g = ds[1:3]
g.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,None
1,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,700,pressure,0,None

In [8]:
g = ds[-1]
g

Field(v, 2018-08-01 12:00:00, 2018-08-01 12:00:00, 0:00:00, 300, pressure, 0, None)

### Getting data values

#### Using values

The :py:attr:`~data.core.fieldlist.Field.values` property always returns a flat array per field:

In [9]:
v = ds[0].values
v.shape

(84,)

In [10]:
v[0:4]

array([272.56486405, 272.56486405, 272.56486405, 272.56486405])

When called on the whole fieldlist :py:attr:`~data.core.fieldlist.FieldList.values` returns a 2D array:

In [11]:
v = ds.values
v.shape

(18, 84)

#### Using to_numpy()

With :py:meth:`~data.core.fieldlist.Field.to_numpy` the field shape is set on the array:

In [12]:
v = ds[0].to_numpy()
print(v.shape)
print(ds[0].shape)

(7, 12)
(7, 12)

In [13]:
v = ds.to_numpy()
v.shape

(18, 7, 12)

### Metadata

Metadata access works both on individual fields and slices:

In [14]:
ds[0].get("parameter.variable")

't'

In [15]:
ds[0:2].get(["vertical.level", "parameter.variable"])

[[1000, 't'], [850, 't']]

and on all the fields:

In [16]:
ds.get("vertical.level")

[1000,
 850,
 700,
 500,
 400,
 300,
 1000,
 850,
 700,
 500,
 400,
 300,
 1000,
 850,
 700,
 500,
 400,
 300]

For each filed we can get the metadata as an object:

### Selection

Selection by metadata is always creating a "view", no copying of data is involved.

In [17]:
g = ds.sel({"parameter.variable": ['u', 'v'], "vertical.level": 850})
g.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,None
1,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,None

In [18]:
g = ds.sel({"parameter.variable": "t"})
g.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,None
1,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,None
2,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,700,pressure,0,None
3,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,500,pressure,0,None
4,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,400,pressure,0,None
5,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,300,pressure,0,None

### Xarray

Xarray conversion does not involve disk writing.

In [19]:
ds1 = ds.to_xarray()
ds1

<xarray.Dataset> Size: 12kB
Dimensions:    (time: 1, level: 6, latitude: 7, longitude: 12)
Coordinates:
  * time       (time) datetime64[ns] 8B 2018-08-01T12:00:00
  * level      (level) int32 24B 1000 850 700 500 400 300
  * latitude   (latitude) float32 28B 90.0 60.0 30.0 0.0 -30.0 -60.0 -90.0
  * longitude  (longitude) float32 48B 0.0 30.0 60.0 90.0 ... 270.0 300.0 330.0
Data variables:
    t          (time, level, latitude, longitude) float64 4kB dask.array<chunksize=(1, 6, 7, 12), meta=np.ndarray>
    u          (time, level, latitude, longitude) float64 4kB dask.array<chunksize=(1, 6, 7, 12), meta=np.ndarray>
    v          (time, level, latitude, longitude) float64 4kB dask.array<chunksize=(1, 6, 7, 12), meta=np.ndarray>
Attributes:
    Conventions:  CF-1.6
    history:      2023-08-07 18:24:35 GMT by grib_to_netcdf-2.30.2: grib_to_n...