## Retrieving data from the ADS

The :ref:`ads <data-sources-ads>` data source provides access to the `Copernicus Atmosphere Data Store (ADS) <https://ads.atmosphere.copernicus.eu>`_.

In [1]:
import earthkit.data as ekd

### Getting GRIB data

In [2]:
ds = ekd.from_source(
    "ads",
    "cams-global-reanalysis-eac4",
    request=dict(
        variable=["particulate_matter_10um", "particulate_matter_1um"],
        area=[50, -50, 20, 50],  # N,W,S,E
        date="2012-05-10",
        time="12:00",
    ),
)

In [3]:
ds.to_fieldlist().ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,pm10,2012-05-10 12:00:00,2012-05-10 12:00:00,0 days,0,surface,0,regular_ll
1,pm1,2012-05-10 12:00:00,2012-05-10 12:00:00,0 days,0,surface,0,regular_ll

### Getting NetCDF data

In [4]:
ds1 = ekd.from_source(
    "ads",
    "cams-global-reanalysis-eac4",
    request=dict(
        variable=["particulate_matter_10um", "particulate_matter_1um"],
        area=[50, -50, 20, 50],  # N,W,S,E
        date="2012-05-10",
        time="12:00",
        format="netcdf",
    ),
)

In [5]:
ds1.to_fieldlist().ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,pm10,2012-05-10 12:00:00,2012-05-10 12:00:00,0 days,None,unknown,0,None
1,pm1,2012-05-10 12:00:00,2012-05-10 12:00:00,0 days,None,unknown,0,None