# GRIB: listing contents

We will work with a GRIB file containing 6 messages, which we get as a sample (see :ref:`from_source() <data-sources-sample>`).

In [1]:
import earthkit.data as ekd

ds = ekd.from_source("sample", "test6.grib").to_fieldlist()

test6.grib:   0%|          | 0.00/1.41k [00:00<?, ?B/s]

### Using ls(), head() and tail()

All these methods (see e.g.: :py:meth:`~earthkit.data.core.fieldlist.FieldList.ls`) take the same set of keyword arguments.

#### ls()

py:meth:`~earthkit.data.core.fieldlist.FieldList.ls`)  lists all the fields:

In [2]:
ds.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
1,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
2,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
3,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll
4,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll
5,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll

The number of fields can be passed as an argument:

In [3]:
ds.ls(2)

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
1,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll

In [4]:
ds.ls(n=2)

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
1,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll

##### Keys and extra keys

We can use our own list of keys instead of the default ones.

In [5]:
ds.ls(keys="time.base_datetime")

   time.base_datetime
0 2018-08-01 12:00:00
1 2018-08-01 12:00:00
2 2018-08-01 12:00:00
3 2018-08-01 12:00:00
4 2018-08-01 12:00:00
5 2018-08-01 12:00:00

In [6]:
ds.ls(keys=["time.base_datetime", "vertical.level"])

   time.base_datetime  vertical.level
0 2018-08-01 12:00:00            1000
1 2018-08-01 12:00:00            1000
2 2018-08-01 12:00:00            1000
3 2018-08-01 12:00:00             850
4 2018-08-01 12:00:00             850
5 2018-08-01 12:00:00             850

The default list of keys can be extended with ``extra_keys``:

In [7]:
ds.head(extra_keys="parameter.units")

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type,parameter.units
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll,kelvin
1,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll,meter / second
2,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll,meter / second
3,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll,kelvin
4,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll,meter / second

#### tail()

:py:func:`~earthkit.data.core.fieldlist.FieldList.tail` displays the last 5 messages by default:

In [8]:
ds.tail(5)

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
1,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
2,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll
3,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll
4,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll

#### ls()

By default :py:func:`~earthkit.data.fieldlist.FieldList.ls` lists all the fields:

In [9]:
ds.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
1,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
2,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
3,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll
4,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll
5,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll

The number of fields to list can also be specified:

In [10]:
ds.ls(2)

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
1,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll

In [11]:
ds.ls(-2)

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll
1,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll

### Inspecting fields

The simplest ways to inspect a field contents is to use the automatic display.

In [12]:
ds[0]

Field(t, 2018-08-01 12:00:00, 2018-08-01 12:00:00, 0:00:00, 1000, pressure, 0, regular_ll)