# Retrieving data from the CDS

The :ref:`cds <data-sources-cds>` data source provides access to the `Copernicus Climate Data Store (CDS) <https://cds.atmosphere.copernicus.eu>`_.

In [1]:
import earthkit.data as ekd

### Getting GRIB data

In [2]:
d = ekd.from_source(
    "cds",
    "reanalysis-era5-single-levels",
    request=dict(
        variable=["2t", "msl"],
        product_type="reanalysis",
        area=[50, -10, 40, 10],  # N,W,S,E
        grid=[2, 2],
        date="2012-05-10",
        time="12:00",
    ),
)
d

GribData(path=/var/folders/93/w0p869rx17q98wxk83gn9ys40000gn/T/earthkit-data-cgr/cds-retriever-7906c1e5c1676b554722fc7f0eadee8aeadff9a6f8707fea79de39beb2fb21ca.cache)

In [3]:
d.to_fieldlist().ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,2t,2012-05-10 12:00:00,2012-05-10 12:00:00,0 days,0,surface,0,regular_ll
1,msl,2012-05-10 12:00:00,2012-05-10 12:00:00,0 days,0,surface,0,regular_ll

### Getting NetCDF data

In [4]:
d1 = ekd.from_source(
    "cds",
    "reanalysis-era5-single-levels",
    request=dict(
        variable=["2t", "msl"],
        product_type="reanalysis",
        area=[50, -10, 40, 10],  # N,W,S,E
        grid=[2, 2],
        date="2012-05-10",
        time="12:00",
        format="netcdf",
    ),
)
d1

NetCDFData(path=/var/folders/93/w0p869rx17q98wxk83gn9ys40000gn/T/earthkit-data-cgr/cds-retriever-1782892e3a2c6b2a7f0a26a0cde23006146277f2519dd017f9c40986ffd37472.nc)

In [5]:
d1.to_fieldlist().ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t2m,2012-05-10 12:00:00,2012-05-10 12:00:00,0 days,None,unknown,0,None
1,msl,2012-05-10 12:00:00,2012-05-10 12:00:00,0 days,None,unknown,0,None