# Reading tar or zip archive

We :ref:`read <data-sources-file>` a tar file containing 2 GRIB files. First we ensure the example file is available.

In [1]:
import earthkit.data as ekd

ekd.download_example_file("test_gribs.tar")

The files are extracted and stored in the earthkit-data :ref:`cache <caching>`.

In [2]:
d = ekd.from_source("file", "test_gribs.tar")
d

  0%|          | 0/2 [00:00<?, ?it/s]

GribData(path=)

We can convert the data into a fieldlis.

In [3]:
fl = d.to_fieldlist()

In [4]:
fl.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,2t,2020-05-13 12:00:00,2020-05-13 12:00:00,0 days,0,surface,0,regular_ll
1,msl,2020-05-13 12:00:00,2020-05-13 12:00:00,0 days,0,surface,0,regular_ll
2,t,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,500,pressure,0,regular_ll
3,z,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,500,pressure,0,regular_ll
4,t,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,850,pressure,0,regular_ll
5,z,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,850,pressure,0,regular_ll

In [5]:
a = fl.sel({"vertical.level": 500})
a.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,500,pressure,0,regular_ll
1,z,2007-01-01 12:00:00,2007-01-01 12:00:00,0 days,500,pressure,0,regular_ll