# SQL: running a query

The :ref:`data-sources-sql` source runs an SQL query against any database supported by
`SQLAlchemy <https://www.sqlalchemy.org/>`_ (PostgreSQL, MySQL, SQLite, etc.), via the ``sql`` optional
dependency, plus the relevant database driver. It takes a database URL and an SQL query, and only connects to
the database when the data is converted.

The result is a :py:class:`~earthkit.data.data.sql.SQLData` object, which can be converted with ``to_pandas()``
and ``to_geopandas()``.

In this example ``obs.sqlite`` is a small SQLite database containing an ``obs`` table with synthetic
observation data and a ``geom`` geometry column stored as WKB.

In [1]:
db_path = "obs.sqlite"

In [2]:
import earthkit.data as ekd

ds = ekd.from_source("sql", f"sqlite:///{db_path}", "SELECT station, t2m, valid FROM obs WHERE t2m > 285")
ds

SQLData(path=sqlite:///obs.sqlite)

In [3]:
ds.to_pandas()

  station    t2m                valid
0       b  290.0  2026-01-02 06:00:00
1       c  295.0  2026-01-03 12:00:00

## Using query parameters

``:name`` placeholders in the query can be bound to values with ``params``, which is the recommended way to
inject values into a query.

In [4]:
ds = ekd.from_source("sql", f"sqlite:///{db_path}", "SELECT station, t2m FROM obs WHERE t2m > :t")
ds.to_pandas(params={"t": 285})

  station    t2m
0       b  290.0
1       c  295.0

## Reading geometries with `to_geopandas()`

``to_geopandas()`` reads the ``geom`` column (WKB by default, configurable via ``geom_col``) as geometry, using
`geopandas.read_postgis <https://geopandas.org/en/stable/docs/reference/api/geopandas.read_postgis.html>`_.

In [5]:
gdf = ekd.from_source("sql", f"sqlite:///{db_path}", "SELECT * FROM obs").to_geopandas(crs="EPSG:4326")
gdf

  station    t2m                valid         geom
0       a  280.0  2026-01-01 00:00:00  POINT (0 0)
1       b  290.0  2026-01-02 06:00:00  POINT (1 1)
2       c  295.0  2026-01-03 12:00:00  POINT (2 2)

## Keeping credentials out of logs

When the database URL contains a password, it is masked in the object's ``path``, ``repr()`` and HTML
representation, so credentials are not accidentally leaked into logs or notebook outputs.

In [6]:
ds = ekd.from_source("sql", "postgresql://user:secret@host/db", "SELECT * FROM obs")
ds

SQLData(path=postgresql://user:***@host/db)