In [1]:
import os

import earthkit.data as ekd

p = os.path.expanduser("~/git/earthkit-data/tests/data/NUTS_RG_20M_2021_3035.shp.zip")

ds = ekd.from_source("file", p)

  0%|          | 0/5 [00:00<?, ?it/s]

from_source_internal: src= File(CACHE:/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.cpg,TextReader)
from_source_internal: src= File(CACHE:/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.dbf,UnknownReader)
from_source_internal: src= File(CACHE:/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.prj,UnknownReader)
from_source_internal: src= ShapeFileReader(/var/folders/93/w0p869rx17q98wxk83gn9ys40000gn/T/tmpsj2tg6or/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.shp)
from_source_internal: src= File(CACHE:/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.shx,UnknownReader)
MultiSource: sources= [File(CACHE:/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.cpg,TextReader), File(CACHE:/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.dbf,UnknownReader), File(CACHE:/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.prj,UnknownReader), ShapeFileReader(/var/folders/93/w0p869rx17q98wxk83gn9ys40000gn/T/tmpsj2tg6or/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.shp), File(CACHE:/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.shx,UnknownReader)]
MultiSource: sources after _from_sources= [File(CACHE:/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.cpg,TextReader), File(CACHE:/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.dbf,UnknownReader), File(CACHE:/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.prj,UnknownReader), ShapeFileReader(/var/folders/93/w0p869rx17q98wxk83gn9ys40000gn/T/tmpsj2tg6or/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.shp), File(CACHE:/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.shx,UnknownReader)]
MultiSource: sources after mutate and ignore= [ShapeFileReader(/var/folders/93/w0p869rx17q98wxk83gn9ys40000gn/T/tmpsj2tg6or/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.shp)]
from_source_internal: src= ShapeFileReader(/var/folders/93/w0p869rx17q98wxk83gn9ys40000gn/T/tmpsj2tg6or/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.shp)
from_source_internal: src= ShapeFileReader(/var/folders/93/w0p869rx17q98wxk83gn9ys40000gn/T/tmpsj2tg6or/file-993fa390d9ec8bd5ef42887d3997462200234009fea0b28dac8fc36d4b21bcb2.d/NUTS_RG_20M_2021_3035.shp)

In [2]:
ds.available_types

['geopandas', 'pandas', 'xarray', 'geojson']

In [3]:
ds.to_pandas()

,NUTS_ID,LEVL_CODE,CNTR_CODE,NAME_LATN,NUTS_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,FID,geometry
0,FR,0,FR,France,France,0.0,0,0,FR,"MULTIPOLYGON (((9954236.116 -3059379.316, 9961..."
1,HR,0,HR,Hrvatska,Hrvatska,0.0,0,0,HR,"MULTIPOLYGON (((4827385.889 2618351.326, 48483..."
2,HU,0,HU,Magyarország,Magyarország,0.0,0,0,HU,"POLYGON ((5214660.069 2880853.832, 5216710.22 ..."
3,AL,0,AL,Shqipëria,Shqipëria,0.0,0,0,AL,"POLYGON ((5129579.17 2204098.752, 5148385.473 ..."
4,AT,0,AT,Österreich,Österreich,0.0,0,0,AT,"POLYGON ((4742889.368 2876362.725, 4783217.798..."
...,...,...,...,...,...,...,...,...,...,...
2005,TRC21,3,TR,Şanlıurfa,Şanlıurfa,4.0,2,3,TRC21,"POLYGON ((6904684.585 2120354.802, 6938677.828..."
2006,TRC22,3,TR,Diyarbakır,Diyarbakır,4.0,2,3,TRC22,"POLYGON ((6989716.598 2273670.524, 6982786.486..."
2007,NO0B2,3,NO,Svalbard,Svalbard,3.0,3,1,NO0B2,"MULTIPOLYGON (((4754167.335 6382461.409, 47465..."
2008,NO0B,2,NO,Jan Mayen and Svalbard,Jan Mayen and Svalbard,NaN,0,0,NO0B,"MULTIPOLYGON (((4754167.335 6382461.409, 47465..."
2009,NO0B1,3,NO,Jan Mayen,Jan Mayen,3.0,3,1,NO0B1,"POLYGON ((3642785.362 5404637.884, 3624291.51 ..."

In [4]:
fl = ds.to_featurelist()

In [5]:
type(fl)

earthkit.data.readers.shapefile.file.ShapeFileList

In [6]:
fl.head()

,NUTS_ID,LEVL_CODE,CNTR_CODE,NAME_LATN,NUTS_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,FID,geometry
0,FR,0,FR,France,France,0.0,0,0,FR,"MULTIPOLYGON (((9954236.116 -3059379.316, 9961..."
1,HR,0,HR,Hrvatska,Hrvatska,0.0,0,0,HR,"MULTIPOLYGON (((4827385.889 2618351.326, 48483..."
2,HU,0,HU,Magyarország,Magyarország,0.0,0,0,HU,"POLYGON ((5214660.069 2880853.832, 5216710.22 ..."
3,AL,0,AL,Shqipëria,Shqipëria,0.0,0,0,AL,"POLYGON ((5129579.17 2204098.752, 5148385.473 ..."
4,AT,0,AT,Österreich,Österreich,0.0,0,0,AT,"POLYGON ((4742889.368 2876362.725, 4783217.798..."

In [7]:
fl._df

,NUTS_ID,LEVL_CODE,CNTR_CODE,NAME_LATN,NUTS_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,FID,geometry
0,FR,0,FR,France,France,0.0,0,0,FR,"MULTIPOLYGON (((9954236.116 -3059379.316, 9961..."
1,HR,0,HR,Hrvatska,Hrvatska,0.0,0,0,HR,"MULTIPOLYGON (((4827385.889 2618351.326, 48483..."
2,HU,0,HU,Magyarország,Magyarország,0.0,0,0,HU,"POLYGON ((5214660.069 2880853.832, 5216710.22 ..."
3,AL,0,AL,Shqipëria,Shqipëria,0.0,0,0,AL,"POLYGON ((5129579.17 2204098.752, 5148385.473 ..."
4,AT,0,AT,Österreich,Österreich,0.0,0,0,AT,"POLYGON ((4742889.368 2876362.725, 4783217.798..."
...,...,...,...,...,...,...,...,...,...,...
2005,TRC21,3,TR,Şanlıurfa,Şanlıurfa,4.0,2,3,TRC21,"POLYGON ((6904684.585 2120354.802, 6938677.828..."
2006,TRC22,3,TR,Diyarbakır,Diyarbakır,4.0,2,3,TRC22,"POLYGON ((6989716.598 2273670.524, 6982786.486..."
2007,NO0B2,3,NO,Svalbard,Svalbard,3.0,3,1,NO0B2,"MULTIPOLYGON (((4754167.335 6382461.409, 47465..."
2008,NO0B,2,NO,Jan Mayen and Svalbard,Jan Mayen and Svalbard,NaN,0,0,NO0B,"MULTIPOLYGON (((4754167.335 6382461.409, 47465..."
2009,NO0B1,3,NO,Jan Mayen,Jan Mayen,3.0,3,1,NO0B1,"POLYGON ((3642785.362 5404637.884, 3624291.51 ..."