## GRIB: selection using metadata

We read an example GRIB file containing 18 messages and load into a fieldlist.

In [1]:
import earthkit.data as ekd

ds = ekd.from_source("sample", "tuv_pl.grib").to_fieldlist()
len(ds)

18

### Using sel

With :py:meth:`~data.core.FieldList.sel` we can select a subset of messages.

In [2]:
ds1 = ds.sel({"vertical.level": 500})
ds1.ls()

,centre,shortName,typeOfLevel,level,dataDate,dataTime,stepRange,dataType,number,gridType
0,ecmf,t,isobaricInhPa,500,20180801,1200,0,an,0,regular_ll
1,ecmf,u,isobaricInhPa,500,20180801,1200,0,an,0,regular_ll
2,ecmf,v,isobaricInhPa,500,20180801,1200,0,an,0,regular_ll

Lists are accepted:

In [3]:
ds1 = ds.sel({"vertical.level": [500, 850]})
ds1.ls()

,centre,shortName,typeOfLevel,level,dataDate,dataTime,stepRange,dataType,number,gridType
0,ecmf,t,isobaricInhPa,850,20180801,1200,0,an,0,regular_ll
1,ecmf,u,isobaricInhPa,850,20180801,1200,0,an,0,regular_ll
2,ecmf,v,isobaricInhPa,850,20180801,1200,0,an,0,regular_ll
3,ecmf,t,isobaricInhPa,500,20180801,1200,0,an,0,regular_ll
4,ecmf,u,isobaricInhPa,500,20180801,1200,0,an,0,regular_ll
5,ecmf,v,isobaricInhPa,500,20180801,1200,0,an,0,regular_ll

Slices can define closed intervals, so they are treated as inclusive of both the start and stop values, unlike normal Python indexing:

In [4]:
ds1 = ds.sel({"vertical.level": slice(500, 850), "parameter.variable": "t"})
ds1.ls()

Empty DataFrame
Columns: []
Index: []

### Using order_by

:py:meth:`~data.core.FieldList.order_by` returns a sorted fieldlist. First we create a smaller subset for the :py:meth:`~data.core.FieldList.order_by`
examples.

In [5]:
ds1 = ds.sel({"vertical.level": slice(500, 850), 
             "parameter.variable": ["u", "v"]})

In [6]:
ds1.order_by("parameter.variable").ls()

Empty DataFrame
Columns: []
Index: []

The sorting keys can be specified as a list:

In [7]:
ds1.order_by(["parameter.variable", "vertical.level"]).ls()

Empty DataFrame
Columns: []
Index: []

We can prescribe the actual order within a key. It only works when all the possible values are specified:

In [8]:
ds1.order_by({"vertical.level": [500, 850, 700]}).ls()

Empty DataFrame
Columns: []
Index: []

### Combining sel and order_by

In [9]:
ds.sel({"vertical.level": [500, 850]}).order_by(["paramater.variable"]).ls()

,centre,shortName,typeOfLevel,level,dataDate,dataTime,stepRange,dataType,number,gridType
0,ecmf,t,isobaricInhPa,850,20180801,1200,0,an,0,regular_ll
1,ecmf,u,isobaricInhPa,850,20180801,1200,0,an,0,regular_ll
2,ecmf,v,isobaricInhPa,850,20180801,1200,0,an,0,regular_ll
3,ecmf,t,isobaricInhPa,500,20180801,1200,0,an,0,regular_ll
4,ecmf,u,isobaricInhPa,500,20180801,1200,0,an,0,regular_ll
5,ecmf,v,isobaricInhPa,500,20180801,1200,0,an,0,regular_ll