# Using GRIB data

We will work with a GRIB file containing 6 messages. First we ensure the example file is available, then read the file with :ref:`from_source() <data-sources-file>`.

In [1]:
import earthkit.data as ekd

ekd.download_example_file("test6.grib")

In [2]:
ds_in = ekd.from_source("file", "test6.grib")
ds_in

GribData(path={self._reader.path})

We load the GRIB data into a fieldlist.

In [3]:
ds = ds_in.to_fieldlist()

### Iteration

A :ref:`GRIB <grib>` data object is represented by a :py:class:`~data.readers.grib.index.GribFieldList` consisting of :py:class:`~data.core.field.Field`\s. When used in iteration the GRIB data is automatically loaded and released when going out of scope. As a result, during the iteration only one GRIB message at a time is kept in memory:

In [4]:
for f in ds:
    print(f)

Field(t, 2018-08-01 12:00:00, 2018-08-01 12:00:00, 0:00:00, 1000, pressure, 0, regular_ll)
Field(u, 2018-08-01 12:00:00, 2018-08-01 12:00:00, 0:00:00, 1000, pressure, 0, regular_ll)
Field(v, 2018-08-01 12:00:00, 2018-08-01 12:00:00, 0:00:00, 1000, pressure, 0, regular_ll)
Field(t, 2018-08-01 12:00:00, 2018-08-01 12:00:00, 0:00:00, 850, pressure, 0, regular_ll)
Field(u, 2018-08-01 12:00:00, 2018-08-01 12:00:00, 0:00:00, 850, pressure, 0, regular_ll)
Field(v, 2018-08-01 12:00:00, 2018-08-01 12:00:00, 0:00:00, 850, pressure, 0, regular_ll)

### Inspecting the contents

We can use :py:meth:`~data.readers.grib.index.GribFieldList.ls` or :py:meth:`~data.readers.grib.index.GribFieldList.describe`.

In [5]:
len(ds)

6

In [6]:
ds.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
1,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
2,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
3,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll
4,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll
5,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll

### Slicing

Standard Python slicing is available. It does not involve any loading/copying of GRIB data.

In [7]:
g = ds[1]
g.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll

In [8]:
g = ds[1:3]
g.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
1,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll

In [9]:
g = ds[-1]
g.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll

### Getting data values

#### Using values

The :py:attr:`~data.readers.grib.codes.GribField.values` property always returns a flat array per field:

In [10]:
v = ds[0].values
v.shape

(84,)

In [11]:
v[0:4]

array([272.56417847, 272.56417847, 272.56417847, 272.56417847])

When called on the whole fieldlist :py:attr:`~data.readers.grib.index.GribFieldList.values` returns a 2D array:

In [12]:
v = ds.values
v.shape

(6, 84)

#### Using to_numpy()

With :py:meth:`~data.readers.grib.codes.GribField.to_numpy` the field shape is set on the array:

In [13]:
v = ds[0].to_numpy()
v.shape

(7, 12)

:py:meth:`~data.readers.grib.index.GribFieldList.to_numpy` behaves in the same way when called on a fieldlist:

In [14]:
v = ds.to_numpy()
v.shape

(6, 7, 12)

### Fields and metadata

A fieldlist is made up of fields. We can use the automatic display to get a quick overview about what a field contains.

In [15]:
ds[0]

Field(t, 2018-08-01 12:00:00, 2018-08-01 12:00:00, 0:00:00, 1000, pressure, 0, regular_ll)

We use :py:meth:`~data.readers.grib.codes.GribField.get` to access metadata. It works both on individual fields slices or whole fieldlists. The supported metadata keys are format independent.

In [16]:
ds[0].get("vertical.level")

1000

In [17]:
ds[0:2].get(["vertical.level", "parameter.variable"])

[[1000, 't'], [1000, 'u']]

We can also call :py:meth:`~data.readers.grib.index.GribFieldList.metadata` on a fieldlist:

In [18]:
ds.get("vertical.level")

[1000, 1000, 1000, 850, 850, 850]

The underlying ecCodes GRIB metadata keys can also be accessed.

In [19]:
ds[0:2].metadata(["level", "shortName", "centre"])

[[1000, 't', 'ecmf'], [1000, 'u', 'ecmf']]

### Selection

:py:meth:`~data.readers.grib.index.GribFieldList.sel` offers metadata-based selection and always creates a "view", so no copying of GRIB data is involved.

In [20]:
g = ds.sel({"parameter.variable": ["u", "v"], "vertical.level": 850})
g.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,u,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll
1,v,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll

In [21]:
g = ds.sel({"parameter.variable": "t"})
g.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,1000,pressure,0,regular_ll
1,t,2018-08-01 12:00:00,2018-08-01 12:00:00,0 days,850,pressure,0,regular_ll

### Xarray

Converting GRIB to Xarray is based on the earthkit Xarray engine (part of earthkit-data) .

In [22]:
ds.to_xarray()

<xarray.Dataset> Size: 4kB
Dimensions:    (level: 2, latitude: 7, longitude: 12)
Coordinates:
  * level      (level) int64 16B 850 1000
  * latitude   (latitude) float64 56B 90.0 60.0 30.0 0.0 -30.0 -60.0 -90.0
  * longitude  (longitude) float64 96B 0.0 30.0 60.0 90.0 ... 270.0 300.0 330.0
Data variables:
    t          (level, latitude, longitude) float64 1kB ...
    u          (level, latitude, longitude) float64 1kB ...
    v          (level, latitude, longitude) float64 1kB ...
Attributes:
    Conventions:  CF-1.8
    institution:  ECMWF