# Build fieldlist from dicts in a loop

#### Distinct latitudes/longitudes

In this example each field is defined by a dict using generic metadata keys. The latitudes and longitudes specified as disctinct values, the 2D field geometry will be automatically built from them.

In [1]:
prototype = {
    "geography": {"latitudes": [10.0, 0.0, -10.0], "longitudes": [20, 40.0]},
    "values": [1, 2, 3, 4, 5, 6],
    "time": {"valid_datetime": "2018-08-01T09:00:00Z"},
}

d = [
    {"parameter": {"variable": "t"}, "vertical": {"level": 500}, **prototype},
    {"parameter": {"variable": "t"}, "vertical": {"level": 850}, **prototype},
    {"parameter": {"variable": "u"}, "vertical": {"level": 500}, **prototype},
    {"parameter": {"variable": "u"}, "vertical": {"level": 850}, **prototype},
    {"parameter": {"variable": "d"}, "vertical": {"level": 850}, **prototype},
    {"parameter": {"variable": "d"}, "vertical": {"level": 600}, **prototype},
]

Create a fieldlist from the data above in a loop.

In [2]:
from earthkit.data import Field, create_fieldlist

ds = create_fieldlist([Field.from_dict(f) for f in d])

In [3]:
ds.ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,500,unknown,None,_distinct_ll
1,t,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,850,unknown,None,_distinct_ll
2,u,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,500,unknown,None,_distinct_ll
3,u,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,850,unknown,None,_distinct_ll
4,d,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,850,unknown,None,_distinct_ll
5,d,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,600,unknown,None,_distinct_ll

In [4]:
ds[0]

Field(t, 2018-08-01 09:00:00+00:00, 2018-08-01 09:00:00+00:00, 0:00:00, 500, unknown, None, _distinct_ll)

In [5]:
ds[0].geography.latlons()

(array([[ 10.,  10.],
        [  0.,   0.],
        [-10., -10.]]),
 array([[20., 40.],
        [20., 40.],
        [20., 40.]]))

In [6]:
ds.to_numpy()

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [7]:
ds.get("vertical.level")

[500, 850, 500, 850, 850, 600]

In [8]:
ds[0].time.valid_datetime()

datetime.datetime(2018, 8, 1, 9, 0, tzinfo=datetime.timezone.utc)

In [9]:
ds.sel({"parameter.variable": "t"}).ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,500,unknown,None,_distinct_ll
1,t,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,850,unknown,None,_distinct_ll

In [10]:
ds.order_by("vertical.level").ls()

,parameter.variable,time.valid_datetime,time.base_datetime,time.step,vertical.level,vertical.level_type,ensemble.member,geography.grid_type
0,t,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,500,unknown,None,_distinct_ll
1,u,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,500,unknown,None,_distinct_ll
2,d,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,600,unknown,None,_distinct_ll
3,t,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,850,unknown,None,_distinct_ll
4,u,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,850,unknown,None,_distinct_ll
5,d,2018-08-01 09:00:00+00:00,2018-08-01 09:00:00+00:00,0 days,850,unknown,None,_distinct_ll