# Using SQL data

earthkit-data can read tabular data from SQL databases in two ways:

- the :ref:`data-sources-file` source automatically detects SQLite and GeoPackage files and reads them with the
  built-in SQLite reader
- the :ref:`data-sources-sql` source runs an SQL query against any database supported by
  `SQLAlchemy <https://www.sqlalchemy.org/>`_ (PostgreSQL, MySQL, SQLite, etc.), via the ``sql`` optional dependency

Both return a :py:class:`~earthkit.data.data.sql.SQLData` object, which can be converted with ``to_pandas()`` and
``to_geopandas()``.

In this example ``obs.sqlite`` is a small SQLite database containing two tables: ``obs``, with synthetic observation
data and a ``geom`` geometry column stored as WKB (as used e.g. by GeoPackage files), and ``stations``, with the
station names.

In [1]:
db_path = "obs.sqlite"

## Reading an SQLite file with the `file` source

When :func:`from_source` is given a path to a SQLite or GeoPackage file, it is automatically recognised and read
as :ref:`data-sources-sql` data.

In [2]:
import earthkit.data as ekd

ds = ekd.from_source("file", db_path)
ds

SQLData(path=obs.sqlite)

Since the file contains more than one table, ``to_pandas()`` requires ``table`` to select one of them.

In [3]:
try:
    ds.to_pandas()
except ValueError as e:
    print(e)

Expected exactly one table, found 2. Please specify table. Available tables: obs, stations

In [4]:
ds.to_pandas(table="obs")

,station,t2m,valid,geom
0,a,280.0,2026-01-01 00:00:00,b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00...
1,b,290.0,2026-01-02 06:00:00,b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00...
2,c,295.0,2026-01-03 12:00:00,b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00...

In [5]:
ds.to_pandas(table="stations")

  station     name
0       a  Reading
1       b  Bologna
2       c     Bonn

## Reading geometries with `to_geopandas()`

For a plain SQLite file, ``to_geopandas()`` delegates to :func:`geopandas.read_file`, which expects a GeoPackage
(it will not automatically interpret a BLOB column as geometry). To read our ``geom`` column as geometry here,
we use the :ref:`data-sources-sql` source below instead, which supports plain WKB geometry columns via
`geopandas.read_postgis <https://geopandas.org/en/stable/docs/reference/api/geopandas.read_postgis.html>`_.

## Running a query with the `sql` source

The :ref:`data-sources-sql` source takes a database URL and an SQL query, and only connects to the database when
the data is converted. Any database URL supported by SQLAlchemy can be used, e.g. ``"postgresql://user:password@host/db"``;
here we reuse the SQLite file read above.

In [6]:
ds = ekd.from_source("sql", f"sqlite:///{db_path}", "SELECT station, t2m, valid FROM obs WHERE t2m > 285")
ds

SQLData(path=sqlite:///obs.sqlite)

In [7]:
ds.to_pandas()

  station    t2m                valid
0       b  290.0  2026-01-02 06:00:00
1       c  295.0  2026-01-03 12:00:00

``:name`` placeholders in the query can be bound to values with ``params``, which is the recommended way to
inject values into a query.

In [8]:
ds = ekd.from_source("sql", f"sqlite:///{db_path}", "SELECT station, t2m FROM obs WHERE t2m > :t")
ds.to_pandas(params={"t": 285})

  station    t2m
0       b  290.0
1       c  295.0

``to_geopandas()`` reads the ``geom`` column (WKB by default, configurable via ``geom_col``) as geometry.

In [9]:
gdf = ekd.from_source("sql", f"sqlite:///{db_path}", "SELECT * FROM obs").to_geopandas(crs="EPSG:4326")
gdf

  station    t2m                valid         geom
0       a  280.0  2026-01-01 00:00:00  POINT (0 0)
1       b  290.0  2026-01-02 06:00:00  POINT (1 1)
2       c  295.0  2026-01-03 12:00:00  POINT (2 2)

## Keeping credentials out of logs

When the database URL contains a password, it is masked in the object's ``path``, ``repr()`` and HTML
representation, so credentials are not accidentally leaked into logs or notebook outputs.

In [10]:
ds = ekd.from_source("sql", "postgresql://user:secret@host/db", "SELECT * FROM obs")
ds

SQLData(path=postgresql://user:***@host/db)